############## Admin ######################
############## LP ######################
lp_vault_azure_storage_secret: LbbetlgHYs5P7jBmtlepJAKzTVbjOXJzWYV1DfME5kITMUfwP0RiMR5yFIXIu6csEIov3xNQX3Fl99vcs8jkfQ==
 
lp_vault_graph_passport_key: sunbird # can be any random string; to check integrity of content submitted for reviewal
lp_vault_youtube_api_key: AIzaSyBt-urv_p7TuvlIVTikCvpE28MsN-EmFsc

lp_vault_dial_service_authorization: 
